// <auto-generated />
namespace Barebones.Data.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingSomeModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingSomeModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201804170028037_AddingSomeModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
